apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resource-quota
  namespace: dev
spec:
  hard:
    pods: 2
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx1
  name: p1
  namespace: dev
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 200Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resource-quota1
  namespace: dev
spec:
  hard:
    requests.cpu: 500m
    requests.memory: 500Mi
    limits.cpu: "1"
    limits.memory: 1Gi
